-- Managed migration: source-version retention is applied by
-- imbalance_pipeline.storage.migrations.migrate_source_version_retention.
-- It uses a per-table EXCHANGE TABLES state transition, detects a completed
-- exchange on retry, and keeps the former table as a recovery copy.
